<img src="../../img/logo.png" alt="Chmurowisko logo" width="200" align="right">
<br><br>
<br><br>
<br><br>

# Introduction to Azure Kubernetes Services

## LAB Overview

#### This lab will demonstrate:
* How to create cluster using Azure CLI.
* How to create namespace.
* How to deploy POD and service.
* How to create healtcheck

## Task 1: Create AKS cluster

1. In the AWS Management Console, on the **Services** menu, click **IAM**.
2. In the navigation pane on the left, click **Users**.
3. Click on your username.

This will bring to a summary page for user. The **Permissions** tab will be displayed.

4. Review your permissions.
5. Click the **Groups** tab.

What is a name of a group you belong to?

6. Click the **Security credentials** tab.


You will find that Console Access in enabled.

7. Do you have **Access key**: (Yes/No)
8. Can you read **Secret access key**: (Yes/No)
9. In the navigation pane on the left, click **Groups**.

There is a group already created for you: S3-LogAudit.

10. Click the **S3-LogAudit** group.
T
his will bring you to the summary page for the **S3-LogAudit** group.

11. Click the **Permissions** tab.

This group has a Managed Policy associated with it, called AmazonS3ReadOnlyAccess. Managed Policies are pre-built policies (built either by AWS or by your administrators) that can be attached to IAM Users and Groups. When the policy is updated, the changes to the policy are immediately apply against all Users and Groups that are attached to the policy.

12. Under **Actions**, click the **Show Policy** link.

A policy defines what actions are allowed or denied for specific AWS resources. This policy is granting permission to List and Get object from S3. This ability to view resources, but not modify them, is ideal for assigning to an Audit role.

13. Close the **Show Policy** window.


### Business Scenario
For the remainder of this lab, you will work with these Users and Groups to enable permissions supporting the following business scenario:

Your company is expecting and audit. You will be responsible for providing an access to logs stored on the S3 for an auditor.

## Task 2: Create and add User to the Group
You will create an IAM User for an auditor. You will add this user to the **S3-LogAudit** group so that he inherits the necessary permissions via the attached AmazonS3ReadOnlyAccess policy.

#### Create a new user

14. In the left navigation pane, click **Users**.
15. Click **Add user**, and configure following:
    * User name: your_username**_audit** (ex. student1_audit)
    * Access type : select **AWS Management Console access**
    * Console password: leave **Autogenerated password**
16. Leave the rest in default and click **Next:Permissions**.
17. In Set permissions tab select **Add user to group** and then select **S3-LogAudit** group.
18. Click **Next:Review,** and **Create user**.
19. Write down the password and click **Close**.

## Task 3: Sign-In and Test User
In this task, you will test the permissions of the IAM User created in task 2.

20. In the navigation pane on the left, click **Dashboard**.

An **IAM users sign-in link** is displayed It will look similar to:
https://123456789012.signin.aws.amazon.com/console
This is the same link you already used to sign-in to the AWS Account.

21. Copy the **IAM users sign-in** link to the notepad.
22. Open a web browser in a private mode.

**Google Chrome**
* Click the ellipsis at the top-right of the screen
* Click **New incognito window**

**Mozilla Firefox**
* Click the menu bars at the top-right of the screen
* Select **New Private Window**

**Microsoft Edge**
* Click the ellipsis at the top-right of the screen
* Click **New InPrivate window**

**Internet Explorer**
* Click the Tools menu option
* Click **InPrivate Browsing**

**Safari**
* Click **Files** in menu bar
* Select **New Private Window**

23. Paste the **IAM users sign-in** link into your private window and press Enter.
24. Sign-in with:
    * **IAM user name**: username created in step 15
    * **Password**: password copied in step 19
25. In the **Services** menu, click **S3**.
26. Click the name of **chmolabauditcsa** bucket and browse the contents.
    
Since your user is part of the **S3-LogAudit** Group in IAM, they have permission to view a list of Amazon S3 buckets and their contents.

Now, test whether you can put or delete any file from the bucket.

27. Click **Upload** and try to upload random file into the bucket.
You should get similar error: You are not authorized to perform this operation. This is because your user has been assigned permission only to list and get data from Amazon S3.

Next, test whether they have access to Amazon EC2.

28. In the **Services** menu, click **EC2**.
29. In the left navigation pane, click **Instances**.

You cannot see any instances! Instead, it says *An error occurred fetching instance data: You are not authorized to perform this operation..* This is because your user has not been assigned any permissions to use Amazon EC2.

## END LAB
Follow these steps to close the console, end your lab, and delete user created in step 15.

30. Sign **your_username_audit** out of the **AWS Management Console** by configuring the following:
    * At the top of the screen, click **your_username_audit**
    * Click **Sign Out**
31. Go back to your **main** laboratory console.
32. In the **Services** menu, click **IAM**.
33. In the left navigation pane, click **Users**.
34. Select your audit user and click **Delete user**.
35. Confirm by selecting **YES, delete**.

<br><br>

<center><p>&copy; 2019 Chmurowisko Sp. z o.o.<p></center>
